SET STATISTICS TIME ON;
ALTER TABLE ShippingData ADD CONSTRAINT CHK_Capacity CHECK (Capacity > 0);
ALTER TABLE ShippingData ALTER COLUMN Name NVARCHAR(60) NOT NULL;
ALTER TABLE ShippingData ADD CONSTRAINT UQ_Name UNIQUE (Name);
ALTER TABLE ShippingData ALTER COLUMN Year INT NULL;

