SET STATISTICS TIME ON;

BEGIN TRANSACTION;

SAVE TRANSACTION BEFORE_FIRST_DELETION;

DELETE FROM Cargoes WHERE DepartureDate < '2017-01-01';
SELECT * from Cargoes;
ROLLBACK TRANSACTION BEFORE_FIRST_DELETION;

SAVE TRANSACTION BEFORE_SECOND_DELETION;
DELETE FROM Cargoes WHERE DepartureDate < '2017-05-01';
SELECT * from Cargoes;
COMMIT TRANSACTION;

