SET STATISTICS TIME ON;

BEGIN TRANSACTION;

SAVE TRANSACTION BEFORE_FIRST_DELETION;
DELETE FROM Shipments WHERE CustomValue < 1010;
SELECT * from Shipments;
ROLLBACK TRANSACTION BEFORE_FIRST_DELETION;

SAVE TRANSACTION BEFORE_SECOND_DELETION;
DELETE FROM Shipments WHERE CustomValue < 1005;
SELECT * from Shipments;
COMMIT TRANSACTION;