SET STATISTICS TIME ON;

BEGIN TRANSACTION;

SAVE TRANSACTION BEFORE_FIRST_DELETION;
DELETE FROM Ships WHERE Year < 2000;
SELECT * from Ships;
ROLLBACK TRANSACTION BEFORE_FIRST_DELETION;

SAVE TRANSACTION BEFORE_SECOND_DELETION;
DELETE FROM Ships WHERE Year < 2010;
SELECT * from Ships;
COMMIT TRANSACTION;