CREATE TABLE ShippingData (
    RegNumber INT,
    Name NVARCHAR(60),
    Skipper NVARCHAR(60),
    Type NVARCHAR(15),
    Capacity INT,
    Year INT,
    Dockyard NVARCHAR(15),
    CustomValue INT,
    DepartureDate DATE,
    ArriveDate DATE,
    Origin NVARCHAR(20),
    Destination NVARCHAR(20),
    ShipRegNumber INT,
    Number INT,
    Shipment NVARCHAR(30),
    DeclareValue FLOAT,
    Unit NVARCHAR(10),
    InsureValue FLOAT,
    Sender NVARCHAR(30),
    INNsender INT,
    AddressSender NVARCHAR(80),
    Consignee NVARCHAR(30),
    INNconsignee INT,
    BankConsignee NVARCHAR(60),
    AddressConsignee NVARCHAR(80),
    PRIMARY KEY (CustomValue, Number)
);
